language: java

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install rpm -qq

install:
 - cd runtime && mvn package && cd ..

before_script: cd parent
script: mvn package -B

jdk:
  - oraclejdk8
